### ISSUE TITLE
Server joining message

### ISSUE THREAD

**Issue by roshan1337d** [roshan1337d/coding-contests-companion#11] opened 2022-10-01 21:41 UTC
## What needs to be done

When the bot joins a new server, find the first channel in that server where it has permission to send messages, and send an embed with the given information. If there are no such channels where the bot has permission to send messages, ignore.

### Title

HELLO WORLD

### URL

https://github.com/roshan1337d/coding-contests-companion

### Color

1089DF

### Description

```
Thank you for inviting the Coding Contests Companion to this server. It can show ongoing and upcoming contest information, send notifications before one is about to start, and send daily problems from various popular coding platforms. Use the **/help** command for the user guide. If you're facing any difficulties, feel free to **[join the support server.](https://discord.gg/9sDtq74DMn)**
```

## Tips

- The [guildCreate](https://discord.js.org/#/docs/discord.js/main/class/Client?scrollTo=e-guildCreate) client event is triggered whenever the bot joins a new server.
- [Example](https://stackoverflow.com/a/69083062) on how you can find the first channel in the server where the bot has permission to send messages.

**Comment by gaurangk19** [comment] 2022-10-01 21:51
Hey @roshan1337d , I would like to contribute in this. I am new to the open source world but I definitely am willing to learn and grow:-)

**Comment by roshan1337d** [comment] 2022-10-01 21:53
@gaurangk19 You got this 💪
Happy hacktober :)

**Comment by roshan1337d** [comment] 2022-10-04 05:55
@gaurangk19 you still on this, right?

**Comment by gaurangk19** [comment] 2022-10-04 07:31
Hey @roshan1337d, I would love to contribute but I am still learning new things and it will take me a little more time to get working with discord bot. So I will be glad if you assign this issue to someone else, will come back and add new features later :-)

**Comment by roshan1337d** [comment] 2022-10-04 08:55
Sure, no issues. Good luck 👍

This issue is open again for taking. If anyone is interested, tag me here.

**Comment by DevilzzNikhil** [comment] 2022-10-04 09:50
@roshan1337d  may i work on this ??
if the issue is still open ??

**Comment by roshan1337d** [comment] 2022-10-04 12:35
@DevilzzNikhil assigned this to you.. good luck and happy hacktober 🚀

**Comment by DevilzzNikhil** [comment] 2022-10-04 21:10
@roshan1337d  hey i have issue u have node version of 18 but i m using 14 and can udate to 16 max so libraries are clashing what should i do ?

**Comment by DevilzzNikhil** [comment] 2022-10-04 21:11
![Screenshot from 2022-10-05 02-41-15](https://user-images.githubusercontent.com/100992874/193929940-1753cb03-adf2-4df6-b486-bbe8b3de9afe.png)

You can see the error

**Comment by DevilzzNikhil** [comment] 2022-10-04 21:13
![Screenshot from 2022-10-05 02-42-20](https://user-images.githubusercontent.com/100992874/193930169-dc6923eb-554c-49c2-891f-49fb837ba508.png)
I think the error in the discord.js library is due to this only 
@roshan1337d  what u say ??

**Comment by DevilzzNikhil** [comment] 2022-10-04 21:47
I have coded the functionality but not sure it will work or not as node deploy.js shows error in node modules in discord libraries 
@roshan1337d  what should i do ??

**Comment by roshan1337d** [comment] 2022-10-05 03:11
The latest discord.js requires node 16.9.0 or newer as the error suggests. You can download the latest version 18.10.0 from [here](https://nodejs.org/en)

**Comment by DevilzzNikhil** [comment] 2022-10-05 12:14
@roshan1337d  i  am having problem with connection it is beacuse that models are establishing before monogodb connection 
![Screenshot from 2022-10-05 17-39-56](https://user-images.githubusercontent.com/100992874/194057769-a278e1c3-25f2-4cd5-b386-adfa75396696.png)

# Is it issue in the code or issue from my side ??

**Comment by DevilzzNikhil** [comment] 2022-10-05 12:20
should i make new file for connection.js that will use await async @roshan1337d  ??

**Comment by DevilzzNikhil** [comment] 2022-10-05 12:38
@roshan1337d  
## It is reading model before establishing connection i have tried everything from my side please tell

**Comment by DevilzzNikhil** [comment] 2022-10-05 13:55
@roshan1337d  when i am using [link](https://stackoverflow.com/questions/69081782/discord-js-how-to-send-message-when-bot-joins-to-a-new-server-without-system-mes) as channel.permissionsFor(guild.me) return a null object 
I have searched everything on net kinda can you help ??

**Comment by roshan1337d** [comment] 2022-10-05 17:00
@DevilzzNikhil 
```js
const { PermissionFlagsBits } = require('discord.js');
const hasPerm = channel.permissionsFor(client.user).has(PermissionFlagsBits.SendMessages);
```

**Comment by DevilzzNikhil** [comment] 2022-10-05 17:42
![image](https://user-images.githubusercontent.com/100992874/194126159-70d26b42-96ec-418f-aea5-f473566a88e1.png)

Here is the OUTPUT
@roshan1337d

**Comment by roshan1337d** [comment] 2022-10-05 18:59
> @roshan1337d That works good Should I raise pr

Sure thing, good work 👍

**Closed** 2022-10-06 06:19 UTC
Labels: enhancement, help wanted, hacktoberfest
